const $=id=>document.getElementById(id);const app=$('app'),board=$('boardWrap'),reticle=$('reticle'),holo=$('holo'),dock=$('dock'),intro=$('intro'),facts=$('facts'),connector=$('connector');
const DATA=[
 {id:'eligibility',title:'Eligibility & Needs',sub:'Practical readiness before starting',helper:'Land · Water · Capital · Market',main:0,color:'c0',rows:[[4,'Land / shed and fodder space'],[5,'Reliable water supply'],[6,'Starting capital / suitable animals'],[7,'Milk market or collection-centre access']]},
 {id:'opportunities',title:'Opportunities & Challenges',sub:'Income potential and operating risks',helper:'Income · Schemes · Risk · Feed cost',main:1,color:'c1',rows:[[8,'Steady income from milk sales'],[9,'Value-added products and schemes'],[10,'Disease / veterinary-access risk'],[11,'Seasonal feed cost and milk-price changes']]},
 {id:'support',title:'Supporting Activities',sub:'Services that keep the farm operating',helper:'Fodder · Vet/AI · Co-op · Transport',main:2,color:'c2',rows:[[12,'Fodder cultivation and silage'],[13,'Veterinary care and AI services'],[15,'Milk cooperative / collection centre'],[14,'Reliable transport and logistics']]},
 {id:'summary',title:'Readiness Summary',sub:'Final enterprise readiness check',helper:'Resources · Risk · Planning · Support',main:3,color:'c3',rows:[[16,'Resources are ready'],[17,'Risks are understood'],[18,'Business planning and records are in place'],[19,'Support network is connected']]}
];
function pos(i){return `--col:${i%5};--row:${Math.floor(i/5)}`}
$('cards').innerHTML=DATA.map((d,i)=>`<article class="card ${d.color}" data-i="${i}"><div class="icon" style="${pos(d.main)}"></div><div class="ct"><h2>${d.title}</h2><p>${d.helper}</p><span class="tap">TAP TO REVISIT</span></div><div class="arrow">›</div></article>`).join('');
const cards=[...document.querySelectorAll('.card')];let active=null,placed=false,scanning=false,scale=.92,rx=0,ry=0,drag=false,lastX=0,lastY=0,pinchStart=0,startScale=1,timeLeft=131,timerHandle=null;
function guide(a,b){$('guideTitle').textContent=a;$('guideText').textContent=b}function status(a,b){$('statusTitle').textContent=a;$('statusText').textContent=b}function transform(anim=true){board.style.transition=anim?'opacity .35s,transform .35s,left .28s':'none';board.style.transform=`translate(-50%,-50%) scale(${scale}) rotateX(${rx}deg) rotateY(${ry}deg)`;requestAnimationFrame(updateConnector)}
function startTimer(){clearInterval(timerHandle);timeLeft=131;renderTimer();timerHandle=setInterval(()=>{timeLeft=Math.max(0,timeLeft-1);renderTimer();if(!timeLeft)clearInterval(timerHandle)},1000)}function renderTimer(){let m=Math.floor(timeLeft/60),s=timeLeft%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function startPreview(){intro.classList.add('hide');scanning=true;placed=false;reticle.classList.add('show');guide('Find a flat surface','Tap the wooden tabletop area to place the checklist.');status('Scanning surface','Tap anywhere on the table to lock placement.');$('exitBtn').disabled=false;startTimer()}
function placeChecklist(){if(!scanning||placed)return;placed=true;scanning=false;reticle.classList.remove('show');holo.classList.add('show');board.classList.add('show');dock.classList.add('show');$('resetPlacement').disabled=false;guide('✓ Surface locked · Checklist anchored','Tap a milestone for facts · drag to orbit · wheel/pinch to zoom.');status('Checklist ready','4 milestones are revealing.');cards.forEach((c,i)=>setTimeout(()=>c.classList.add('reveal'),i*320))}
function resetPlacement(){closeFacts();placed=false;scanning=true;board.classList.remove('show');holo.classList.remove('show');dock.classList.remove('show');cards.forEach(c=>c.classList.remove('reveal'));reticle.classList.add('show');$('resetPlacement').disabled=true;guide('Scan again','Tap a new position on the tabletop.');status('Scanning surface','Waiting for placement.')}
function exit(){closeFacts();placed=false;scanning=false;board.classList.remove('show');holo.classList.remove('show');dock.classList.remove('show');reticle.classList.remove('show');cards.forEach(c=>c.classList.remove('reveal'));intro.classList.remove('hide');$('resetPlacement').disabled=true;$('exitBtn').disabled=true;clearInterval(timerHandle);timeLeft=131;renderTimer();guide('Start the premium AR preview','Place the checklist on the table and explore all four milestones.');status('Preview ready','Press Start Premium Preview.')}
function openFacts(card){let i=+card.dataset.i,d=DATA[i];active=card;cards.forEach(c=>c.classList.toggle('active',c===card));$('factMain').style.cssText=pos(d.main);$('factTitle').textContent=d.title;$('factSub').textContent=d.sub;$('factList').innerHTML=d.rows.map(r=>`<div class="fact"><div class="icon" style="${pos(r[0])}"></div><span>${r[1]}</span></div>`).join('');facts.classList.add('show');app.classList.add('detail');positionFacts();setTimeout(updateConnector,60)}
function closeFacts(){facts.classList.remove('show');connector.classList.remove('show');cards.forEach(c=>c.classList.remove('active'));active=null}
function positionFacts(){if(!active||innerWidth<760)return;let a=active.getBoundingClientRect(),ph=facts.offsetHeight||390;let y=Math.max(150,Math.min(innerHeight-ph/2-80,a.top+a.height/2));facts.style.top=y+'px'}
function updateConnector(){if(!active||!facts.classList.contains('show')||innerWidth<760){connector.classList.remove('show');return}let br=board.getBoundingClientRect(),a=active.getBoundingClientRect(),f=facts.getBoundingClientRect();let x1=br.right+2,y1=a.top+a.height/2,x2=f.left-8,len=x2-x1;if(len<18){connector.classList.remove('show');return}connector.style.left=x1+'px';connector.style.top=y1+'px';connector.style.width=len+'px';connector.classList.add('show')}
$('startBtn').onclick=startPreview;$('room').addEventListener('click',e=>{if(scanning)placeChecklist()});reticle.addEventListener('click',placeChecklist);cards.forEach(c=>c.onclick=()=>openFacts(c));$('closeFacts').onclick=closeFacts;$('resetPlacement').onclick=resetPlacement;$('exitBtn').onclick=exit;
$('zoomIn').onclick=()=>{scale=Math.min(1.3,scale+.08);transform()};$('zoomOut').onclick=()=>{scale=Math.max(.65,scale-.08);transform()};$('focusBtn').onclick=()=>{scale=1;rx=0;ry=0;transform()};$('resetView').onclick=()=>{scale=.92;rx=0;ry=0;transform()};
board.addEventListener('wheel',e=>{if(!placed)return;e.preventDefault();scale=Math.max(.65,Math.min(1.3,scale+(e.deltaY<0?.05:-.05)));transform(false)},{passive:false});board.addEventListener('pointerdown',e=>{if(e.target.closest('.card'))return;drag=true;lastX=e.clientX;lastY=e.clientY;board.setPointerCapture?.(e.pointerId)});board.addEventListener('pointermove',e=>{if(!drag)return;ry+= (e.clientX-lastX)*.08;rx-= (e.clientY-lastY)*.06;rx=Math.max(-14,Math.min(14,rx));ry=Math.max(-20,Math.min(20,ry));lastX=e.clientX;lastY=e.clientY;transform(false)});board.addEventListener('pointerup',()=>drag=false);board.addEventListener('pointercancel',()=>drag=false);
board.addEventListener('touchstart',e=>{if(e.touches.length===2){pinchStart=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);startScale=scale}},{passive:true});board.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinchStart){let d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);scale=Math.max(.65,Math.min(1.3,startScale*d/pinchStart));transform(false)}},{passive:true});
addEventListener('keydown',e=>{if(e.key==='+'){scale=Math.min(1.3,scale+.08);transform()}if(e.key==='-'){scale=Math.max(.65,scale-.08);transform()}if(e.key.toLowerCase()==='f'){$('focusBtn').click()}if(e.key.toLowerCase()==='r'){$('resetView').click()}if(e.key==='Escape'){if(facts.classList.contains('show'))closeFacts();else if(placed||scanning)exit()}});addEventListener('resize',()=>{positionFacts();updateConnector()});transform(false);renderTimer();